### ISSUE TITLE
Add .pes as supported file extension

### ISSUE THREAD

**Issue by afaup** [MartinHvi/abaqus-syntax-highlighting#11]
Hi Martin,

I really appreciate this extension for VS Code and use it daily! Could you please add .pes as a supported file extension? 
If you do not know, a file with this extension is generated when a parameterized input (.inp) file is pre-processed by Abaqus (when the *parameter keyword is used). I edit these files quite a bit and they are also an automatically accepted input file for the analysis job without specifying input=... in the analysis execution command.

For more information:
https://help.3ds.com/HelpDS.aspx?V=2023&P=dssimulia_established&L=english&contextscope=all&F=simacaemodrefmap/simamod-c-parinput.htm#simamod-c-parinput-t-ExecutionOfParametrizedInput-sma-topic19

Thanks!
Alex

**Comment by MartinHvi** [comment]
Hello Alex,

I'm glad to hear that you find the extension useful. Adding support for the .pes file extension should be a quick fix. I will add it as soon as possible :)

**Comment by afaup** [comment]
I'm taking advantage of the enhancement. Thanks!
